### ISSUE TITLE
Migration fails to find user table

### ISSUE THREAD

**Issue by bkuberek** [django-guardian/django-guardian#230]
Running `migrate` is failing with the error below. Guardian is looking for a table named `portal_user` while my user table's name is `users`

User class:
```python
class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        app_label = 'portal'
        db_table = 'users'
        verbose_name = _('user')
        verbose_name_plural = _('users')
        ordering = ['username']
```
settings.py
```python
AUTH_USER_MODEL = 'portal.User'
```
Error: 
```
    2014-06-27 14:50:03.371 [9719]: execute "ALTER TABLE "guardian_userobjectpermission" ADD CONSTRAINT "user_id_refs_id_1fa6f88df1fef45a" FOREIGN KEY ("user_id") REFERENCES "portal_user" ("id") DEFERRABLE INITIALLY DEFERRED;" with params "[]"
    FATAL ERROR - The following SQL query failed: ALTER TABLE "guardian_userobjectpermission" ADD CONSTRAINT "user_id_refs_id_1fa6f88df1fef45a" FOREIGN KEY ("user_id") REFERENCES "portal_user" ("id") DEFERRABLE INITIALLY DEFERRED;
    The error was: relation "portal_user" does not exist

    Error in migration: guardian:0001_initial
    Traceback (most recent call last):
      File "./bin/spemployee", line 11, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python2.6/dist-packages/Django-1.6.2-py2.6.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.6/dist-packages/Django-1.6.2-py2.6.egg/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python2.6/dist-packages/Django-1.6.2-py2.6.egg/django/core/management/base.py", line 242, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/usr/local/lib/python2.6/dist-packages/Django-1.6.2-py2.6.egg/django/core/management/base.py", line 285, in execute
        output = self.handle(*args, **options)
      File "/usr/lib/python2.6/dist-packages/south/management/commands/migrate.py", line 107, in handle
        ignore_ghosts = ignore_ghosts,
      File "/usr/lib/python2.6/dist-packages/south/migration/__init__.py", line 219, in migrate_app
        success = migrator.migrate_many(target, workplan, database)
      File "/usr/lib/python2.6/dist-packages/south/migration/migrators.py", line 235, in migrate_many
        result = migrator.__class__.migrate_many(migrator, target, migrations, database)
      File "/usr/lib/python2.6/dist-packages/south/migration/migrators.py", line 310, in migrate_many
        result = self.migrate(migration, database)
      File "/usr/lib/python2.6/dist-packages/south/migration/migrators.py", line 133, in migrate
        result = self.run(migration)
      File "/usr/lib/python2.6/dist-packages/south/migration/migrators.py", line 107, in run
        return self.run_migration(migration)
      File "/usr/lib/python2.6/dist-packages/south/migration/migrators.py", line 82, in run_migration
        south.db.db.execute_deferred_sql()
      File "/usr/lib/python2.6/dist-packages/south/db/generic.py", line 309, in execute_deferred_sql
        self.execute(sql)
      File "/usr/lib/python2.6/dist-packages/south/db/generic.py", line 273, in execute
        cursor.execute(sql, params)
      File "/usr/local/lib/python2.6/dist-packages/Django-1.6.2-py2.6.egg/django/db/backends/util.py", line 69, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/usr/local/lib/python2.6/dist-packages/Django-1.6.2-py2.6.egg/django/db/backends/util.py", line 53, in execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python2.6/dist-packages/Django-1.6.2-py2.6.egg/django/db/utils.py", line 99, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/usr/local/lib/python2.6/dist-packages/Django-1.6.2-py2.6.egg/django/db/backends/util.py", line 53, in execute
        return self.cursor.execute(sql, params)
    django.db.utils.ProgrammingError: relation "portal_user" does not exist
```

**Comment by brianmay** [comment]
This sounds to me like a dependency issue in the Django South migrations. The guardian migrations are being run before the required tables are created. An issue that should be fixed in the Django 1.7 migrations.

It also sounds like the work around given is exactly what would be required to resolve this issue.

As Django < 1.7 is no longer supported, and may get removed from this project - see #350 - am closing this ticket.
