### ISSUE TITLE
Django 1.8 error with 1.2.5 and GuardedModelAdmin

### ISSUE THREAD

**Issue by autrilla** [django-guardian/django-guardian#308]
My tests (not admin tests, just general model tests) that passed without using GuardedModelAdmin now don't pass, I get the following traceback:

```
Error
Traceback (most recent call last):
  File "/home/autrilla/FarmNet/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/autrilla/PycharmProjects/FarmNet/farmmanager/tests.py", line 21, in test_farm_url
    url = reverse('farmmanager:farm', args=['pig-farm', ])
  File "/home/autrilla/FarmNet/lib/python3.4/site-packages/django/core/urlresolvers.py", line 550, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/autrilla/FarmNet/lib/python3.4/site-packages/django/core/urlresolvers.py", line 352, in app_dict
    self._populate()
  File "/home/autrilla/FarmNet/lib/python3.4/site-packages/django/core/urlresolvers.py", line 285, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/autrilla/FarmNet/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/autrilla/FarmNet/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/autrilla/PycharmProjects/FarmNet/FarmNet/urls.py", line 9, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "/home/autrilla/FarmNet/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 291, in urls
    return self.get_urls(), 'admin', self.name
  File "/home/autrilla/FarmNet/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 275, in get_urls
    url(r'^%s/%s/' % (model._meta.app_label, model._meta.model_name), include(model_admin.urls)),
  File "/home/autrilla/FarmNet/lib/python3.4/site-packages/django/contrib/admin/options.py", line 631, in urls
    return self.get_urls()
  File "/home/autrilla/FarmNet/lib/python3.4/site-packages/guardian/admin.py", line 107, in get_urls
    info = self.model._meta.app_label, self.model._meta.module_name
AttributeError: 'Options' object has no attribute 'module_name'
```

As the title says I'm using django 1.8 and guardian 1.2.5, the latest version available on pip.

**Comment by evandavey** [comment]
+1

**Comment by thedrow** [comment]
@lukaszb Was this resolved? It is in 1.3? Can we close it?

**Comment by gabn88** [comment]
same issue...

**Comment by brianmay** [comment]
@gabn88 What version did you test with? If with a recent release or latest git version, you please quote the stack trace?

**Comment by brianmay** [comment]
I believe this was fixed. If it can still be reproduced, let me know and I will reconsider. For now, closing this report.
