### ISSUE TITLE
example_project broken

### ISSUE THREAD

**Issue by brianmay** [django-guardian/django-guardian#364]
This is used by some of the tox tests. It is not used by the travis tests.

```
CommandError: One or more models did not validate:
testapp.customuser: Accessor for m2m field 'groups' clashes with related m2m field 'Group.customuser_set'. Add a related_name argument to the definition for 'groups'.
testapp.customuser: Accessor for m2m field 'user_permissions' clashes with related m2m field 'Permission.customuser_set'. Add a related_name argument to the definition for 'user_permissions'.
core.customuser: Accessor for m2m field 'groups' clashes with related m2m field 'Group.customuser_set'. Add a related_name argument to the definition for 'groups'.
core.customuser: Accessor for m2m field 'user_permissions' clashes with related m2m field 'Permission.customuser_set'. Add a related_name argument to the definition for 'user_permissions'.
```

**Comment by Wtower** [comment]
To elaborate on this, I tried to evaluate for different versions. Regarding Python, results are consistent for both 2.7 and 3.4.

With Django 1.5 and 1.6 the error is as @brianmay describes above, and this also occurs on `syncdb` and not only tests.

With Django 1.7 and 1.8 we get:

    Traceback (most recent call last):
      File "./manage.py", line 17, in <module>
        execute_from_command_line(sys.argv)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
        django.setup()
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
        app_config.ready()
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/contrib/admin/apps.py", line 22, in ready
        self.module.autodiscover()
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 23, in autodiscover
        autodiscover_modules('admin', register_to=site)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
        import_module('%s.%s' % (app_config.name, module_to_search))
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/home/gkarak/workspace/python/django-guardian/example_project/posts/admin.py", line 3, in <module>
        from example_project.posts.models import Post
      File "/home/gkarak/workspace/python/django-guardian/example_project/posts/models.py", line 4, in <module>
        class Post(models.Model):
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/db/models/base.py", line 286, in __new__
        new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/apps/registry.py", line 213, in register_model
        (model_name, app_label, app_models[model_name], model))
    RuntimeError: Conflicting 'post' models in application 'posts': <class 'posts.models.Post'> and <class 'example_project.posts.models.Post'>.

With Django 1.9 we get:

    Traceback (most recent call last):
      File "./manage.py", line 17, in <module>
        execute_from_command_line(sys.argv)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
        utility.execute()
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/core/management/__init__.py", line 302, in execute
        settings.INSTALLED_APPS
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/conf/__init__.py", line 55, in __getattr__
        self._setup(name)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/conf/__init__.py", line 43, in _setup
        self._wrapped = Settings(settings_module)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/conf/__init__.py", line 99, in __init__
        mod = importlib.import_module(self.SETTINGS_MODULE)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/home/gkarak/workspace/python/django-guardian/example_project/settings.py", line 85, in <module>
        'django.core.context_processors.static',
    TypeError: can only concatenate list (not "tuple") to list

If we change `settings.py` lines 82-86 (devel Dec 12) the setting `TEMPLATE_CONTEXT_PROCESSORS` append from list to tuple as:

    TEMPLATE_CONTEXT_PROCESSORS = global_settings.TEMPLATE_CONTEXT_PROCESSORS + [
        'django.core.context_processors.request',
        'example_project.context_processors.version',
        'django.core.context_processors.static',
    ]

Then we get the same error as above for versions 1.7, 1.8.

But obviously the above change does not work as is for versions 1.5-1.8 because then we would get:

    Traceback (most recent call last):
      File "./manage.py", line 17, in <module>
        execute_from_command_line(sys.argv)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
        utility.execute()
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/core/management/__init__.py", line 392, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/core/management/__init__.py", line 263, in fetch_command
        app_name = get_commands()[subcommand]
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/core/management/__init__.py", line 109, in get_commands
        apps = settings.INSTALLED_APPS
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/conf/__init__.py", line 52, in __getattr__
        self._setup(name)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/conf/__init__.py", line 47, in _setup
        self._wrapped = Settings(settings_module)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/conf/__init__.py", line 130, in __init__
        mod = importlib.import_module(self.SETTINGS_MODULE)
      File "/home/gkarak/.virtualenvs/django-guardian3/lib/python3.4/site-packages/django/utils/importlib.py", line 35, in import_module
        __import__(name)
      File "/home/gkarak/workspace/python/django-guardian/example_project/settings.py", line 85, in <module>
        'django.core.context_processors.static',
    TypeError: can only concatenate tuple (not "list") to tuple

Would love to help but further on I got no clue where to start from.

**Comment by brianmay** [comment]
There is already a testapp under `guardian/testapp`.

I find it a bit confusing that there is `guardian/testapp` and `example_project`.

The automatic tests use `guardian/testapp` however there are some tests referenced from `tox.ini` that use `example_project`.

Does `example_project` provide anything not provided by `guardian/testapp`? If so, maybe we can delete `example_project`? Otherwise maybe we can merge  `example_project` into `guardian/testapp`?

Otherwise we need to be clear about what the role is for each of these directories.

**Comment by brianmay** [comment]
Forgot to say, all the tests under `guardian/testapp` should be working fine.

**Comment by Wtower** [comment]
I see. But how to invoke the tests in `guardian/testapp` without a proper project? There is no`manage.py` or settings file for that. My understanding is that tests should be able to run from within any project.

So this is where `example_project` probably fits in. Maybe somebody older in the project such as @lukaszb could enlighten us.

I may understand the logic behind an "example project". It is like how you could use several features of the app, Guardian, including the tests. This could even be a separate repo all together.

**Comment by brianmay** [comment]
There is no reason why `guardian/testapp` couldn't have a `manage.py` too. Its settings are currently in `guardian/testsettings.py` - possibly these should get moved to `guardian/testapp`.

You could make the argument that the example_project is more for documentation purposes and guardian/testapp is more for automatic tests.

However the way it is at the moment, tox will try to run automatic tests on both.

You could also make the argument that even if example_project is for documentation purposes, we should still test it. However the travis tests don't touch example_project. Plus even the tox tests for example_project don't test with the full range of Python and Django versions.

A bit of consistency between the tox and travis tests would be good.

**Comment by Wtower** [comment]
Ok so I created a `manage.py` for `guardian/testapp` and also moved `guardian/testsettings.py` to `guardian/testapp/testsettings.py`. All these can be seen in this [branch of my fork](https://github.com/Wtower/django-guardian/tree/example-project-broken/guardian/testapp).

But in `manage.py` the `DJANGO_SETTINGS_MODULE` env is apparently wrong, how should that be to get it working?

Regarding the rest of your comment, it sounds reasonable to me. Unfortunately my experience with tox is null to help more with improving on these tests.

**Comment by brianmay** [comment]
I would have thought what you have is correct.

Oh, I see, the problem is that the python search path isn't being set correctly. The following works for me.

```
PYTHONPATH=. ./guardian/testapp/manage.py
```

**Comment by Wtower** [comment]
But of course, how I missed that. The current path of `manage.py` is not enough. Adding `../../` (`djangoguardian/`) is good. Added it with `sys.path.append` and it all works fine.

In Django 1.9 we get some deprecation warnings which are quite common to many other apps as well. I am going to open some new issue and deal with them.

Should I add to the testing documentation how to run tests with `testapp/manage.py` as well?

I can now move on with my other issue with system checks.

**Comment by brianmay** [comment]
At the moment all tests are run using "python setup.py test". Which normally wouldn't work for Django applications, however we override `test_suite` and use the `tests.py` file.

So you could also run the tests by executing tests.py directly too.

It sounds like your way of invoking the tests could be better, especially due to the `--parallel` option.

I am guessing it should be possible to adapt tests.py to use `--parallel` as well.

**Comment by Wtower** [comment]
I see. Then adapting tests.py needs to be done. Also the issue with example_project still remains. I am not sure on how to proceed from here, but anyway I created a pull request for the above changes so far.

**Comment by brianmay** [comment]
Before I look at trying to fix the example_project, what are the requirements we need to satisfy?

I can think of just one:

* Automatic tests for continuous integration.

Possibly we could have a demonstration of what a project could look like. However example_project does not satisfy this, as it includes references to things like `guardian.testapp`, and no real code should be using `guardian.testapp`.

I am inclined to update example_project to make it an example project for the documentation, and move the CI tests to `guardian.testapp`.
