### ISSUE TITLE
Cannot build from clone or download

### ISSUE THREAD

**Issue by pombredanne** [django-guardian/django-guardian#445]
As a follow up to my comments in #443
> I am facing the same issue. My head was spinning while trying to figure out how a simple setup.py versions was guessed .... Could there be a simpler, more explicit way that would be friendly to forks and temp dev releases? like using version="1.4.5" in setup.py .... eventually using bumpversion to propagate that in multiple places explicitly?
> To get an idea by what I mean see this branch here: https://github.com/pombredanne/django-guardian/tree/simple-setup and https://pypi.python.org/pypi/django-guardian-on-wheels

... here is an example of trying to build from sources by getting the zip from the tip of devel at https://github.com/django-guardian/django-guardian/archive/88b71cf27ea3d2e01a8f9e2f9f290c8b7651a61b.zip
```
pombreda@COMPUTER:~/w421/django-guardian$ pip install https://github.com/django-guardian/django-guardian/archive/88b71cf27ea3d2e01a8f9e2f9f290c8b7651a61b.zip
Collecting https://github.com/django-guardian/django-guardian/archive/88b71cf27ea3d2e01a8f9e2f9f290c8b7651a61b.zip
  Downloading https://github.com/django-guardian/django-guardian/archive/88b71cf27ea3d2e01a8f9e2f9f290c8b7651a61b.zip
     | 235kB 1.2MB/s
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/easy_install-jCa9Nu/pytest-runner-2.9/.eggs/setuptools_scm-1.11.1-py2.7.egg
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-Os9BDB-build/.eggs/pytest_runner-2.9-py2.7.egg
    Searching for setuptools_scm
    Reading https://pypi.python.org/simple/setuptools_scm/
    Best match: setuptools-scm 1.11.1
    Downloading https://pypi.python.org/packages/84/aa/c693b5d41da513fed3f0ee27f1bf02a303caa75bbdfa5c8cc233a1d778c4/setuptools_scm-1.11.1.tar.gz#md5=4d19b2bc9580016d991f665ac20e2e8f
    Processing setuptools_scm-1.11.1.tar.gz
    Writing /tmp/easy_install-xmUJoJ/setuptools_scm-1.11.1/setup.cfg
    Running setuptools_scm-1.11.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xmUJoJ/setuptools_scm-1.11.1/egg-dist-tmp-Hi0Jqp
    Moving setuptools_scm-1.11.1-py2.7.egg to /tmp/pip-Os9BDB-build/.eggs
    
    Installed /tmp/pip-Os9BDB-build/.eggs/setuptools_scm-1.11.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-Os9BDB-build/setup.py", line 57, in <module>
        cmdclass={'flakes': RunFlakesCommand},
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/pombreda/w421/minecode/local/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/pombreda/w421/minecode/local/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/setuptools_scm/integration.py", line 19, in version_keyword
      File "build/bdist.linux-x86_64/egg/setuptools_scm/__init__.py", line 104, in get_version
      File "build/bdist.linux-x86_64/egg/setuptools_scm/__init__.py", line 82, in _do_parse
    LookupError: setuptools-scm was unable to detect version for '/tmp/pip-Os9BDB-build'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Os9BDB-build/
```

**Comment by brianmay** [comment]
Yes, this is a known limitation in setuptools-scm. I would not recommend using development versions in this way; this is what releases are for. I just released version 1.4.5 so this shouldn't be an issue.

**Comment by pombredanne** [comment]
@brianmay but what are the benefit of setuptools-scm then? It sounds awfully complex for something as simple as a version that is changed only now and then? 

Short of maintaining a fork without it like I did above, this robbing me the ability to use any devel version then?

**Comment by RonnyPfannschmidt** [comment]
a simple workaround is to puload the versions you want/need to a local devpi server you control

thanks to setuptools_scm you will even get a new version number for each of those, thus be able to do audit trails in detail

**Comment by pombredanne** [comment]
@RonnyPfannschmidt what to you mean by puload?

**Comment by RonnyPfannschmidt** [comment]
whops, typo, meant upload

**Comment by ad-m** [comment]
I would like mark that it might make fail fork in TravisCI with stacktrace:
```
$ py.test --cov=guardian

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7.9/bin/py.test", line 9, in <module>

    load_entry_point('pytest==2.6.4', 'console_scripts', 'py.test')()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 32, in main

    config = _prepareconfig(args, plugins)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 85, in _prepareconfig

    pluginmanager=pluginmanager, args=args)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__

    return self._docall(methods, kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall

    res = mc.execute()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute

    res = method(**kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/helpconfig.py", line 27, in pytest_cmdline_parse

    config = __multicall__.execute()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute

    res = method(**kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 636, in pytest_cmdline_parse

    self.parse(args)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 747, in parse

    self._preparse(args)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/config.py", line 719, in _preparse

    args=args, parser=self._parser)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__

    return self._docall(methods, kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall

    res = mc.execute()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute

    res = method(**kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/capture.py", line 52, in pytest_load_initial_conftests

    return __multicall__.execute()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute

    res = method(**kwargs)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytest_django/plugin.py", line 236, in pytest_load_initial_conftests

    settings.DATABASES

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__

    self._setup(name)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup

    self._wrapped = Settings(settings_module)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__

    mod = importlib.import_module(self.SETTINGS_MODULE)

  File "/opt/python/2.7.9/lib/python2.7/importlib/__init__.py", line 37, in import_module

    __import__(name)

  File "/home/travis/build/ad-m/django-guardian/guardian/__init__.py", line 11, in <module>

    VERSION = tuple([int(each) for each in __version__split__[:3]] + __version__split__[3:])

ValueError: invalid literal for int() with base 10: 'dev51+n2f7cb1a'

```

Example: https://travis-ci.org/ad-m/django-guardian/jobs/151879261

It make a debug TravisCI build a lot of harder. I also have doubts about the usefulness of ```setuptools-scm``` as @pombredanne.

**Comment by pombredanne** [comment]
@ad-m wrote:
> It make a debug TravisCI build a lot of harder. I also have doubts about the usefulness of setuptools-scm as @pombredanne.

`<rant>` 
My personal take is that setuptools_scm can make a lot of sense for someone like Jason that maintains 50 to 100 different packages and does fast paced releases and automated the heck of out this use case and uses mercurial primarily: it makes in this case the maintainer life a lot of easier at that scale... at the expense of the users for the use case at hand here. For other uses like here, and when using git that is lacking some of the mercurial sophistication, I am not seeing the value of it when compared to a static version eventually managed by `bumpversion` or similar if needed in several files. `</rant>`

**Comment by RonnyPfannschmidt** [comment]
note - the code in traceback is a completely halfassed implementation of version splitting entirely incorrect for any kind of rich standard compliant version string - so its not surprising it falls over a version strings that includes commit references and a dev tag with the distance in commits to the last release

**Comment by RonnyPfannschmidt** [comment]
on secondary inspection, i concurr i am wrong tho, its an issue with travis shallow clones and the default fallback having only 2 digits

**Comment by pombredanne** [comment]
See https://github.com/pypa/setuptools_scm/issues/94  and https://github.com/pypa/setuptools_scm/pull/410 ... It may work for you

**Comment by Natgho** [comment]
Issue is outdated, if you encounter this issue, try this;
`uv build`
here is example result;
```bash
/P/django-guardian (main)> uv build
uv build
Building source distribution...
...
adding 'guardian/testapp/tests/templates/500.html'
adding 'guardian/testapp/tests/templates/blank.html'
adding 'guardian/testapp/tests/templates/dummy403.html'
adding 'guardian/testapp/tests/templates/dummy404.html'
adding 'guardian/testapp/tests/templates/list.html'
adding 'django_guardian-3.1.2.dist-info/METADATA'
adding 'django_guardian-3.1.2.dist-info/WHEEL'
adding 'django_guardian-3.1.2.dist-info/top_level.txt'
adding 'django_guardian-3.1.2.dist-info/RECORD'
removing build/bdist.macosx-15.3-arm64/wheel
Successfully built dist/django_guardian-3.1.2.tar.gz
Successfully built dist/django_guardian-3.1.2-py3-none-any.whl

```
