### ISSUE TITLE
GUARDIAN_GET_INIT_ANONYMOUS_USER should be commented out after first migration

### ISSUE THREAD

**Issue by hnykda** [django-guardian/django-guardian#473]
Hi. When using [custom user model](http://django-guardian.readthedocs.io/en/v1.2/userguide/custom-user-model.html), you need to specify `GUARDIAN_GET_INIT_ANONYMOUS_USER`. But it should be noted that you need to comment this out after running first migration! Otherwise, it will somehow try to create that user every migration and hence failing on UNIQUE constraint. By removing this, it creates an AnonymousUser (improperly with different fields), but at least doesn't fail...

```
$ ./manage.py migrate account
Operations to perform:
  Apply all migrations: account
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/guardian/management/__init__.py", line 33, in create_anonymous_user
    User.objects.get(**lookup)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
extendedUser.models.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: extendedUser_user.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 224, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
    **kwargs
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/guardian/management/__init__.py", line 38, in create_anonymous_user
    user.save()
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/contrib/auth/base_user.py", line 80, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/dan/.local/opt/miniconda3/envs/djangobase/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: extendedUser_user.email
```

**Comment by ad-m** [comment]
Hello,

I don't receive think issues on my installlation.  In my app even for custom user models the defaults settings works nice.

How looks your model and function specified in ``GUARDIAN_GET_INIT_ANONYMOUS_USER``? Do you can provide source code of them?

What do you receive for
``
> from guardian.compat import get_user_model
> User = get_user_model()
> print(User.USERNAME_FIELD)
> print(guardian_settings.ANONYMOUS_USER_NAME)
> priint(User.objects.filter(**{User.USERNAME_FIELD: guardian_settings.ANONYMOUS_USER_NAME}).all())
``

**Comment by hnykda** [comment]
Hi, sorry - I have already moved to different variant of object level permissions and would be painful trying to get back (it's been about a month).
