### ISSUE TITLE
Sample Project

### ISSUE THREAD

**Issue by hvilela** [django-guardian/django-guardian#478]
I just download the project and tried to run the sample project following these steps:
https://django-guardian.readthedocs.io/en/stable/userguide/example_project.html

Got these erros:

```
MacBook-Pro-de-Henrique-2:example_project hvilela$ ./manage.py runserver
Performing system checks...

System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DIRS, TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_DEBUG, TEMPLATE_LOADERS.

System check identified 1 issue (0 silenced).
December 17, 2016 - 17:48:14
Django version 1.9.4, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/Library/Python/2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 204, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 260, in bind_template
    updates.update(processor(self.request))
  File "/Users/hvilela/Downloads/django-guardian-devel/example_project/core/context_processors.py", line 5, in version
    return {'version': guardian.get_version()}
AttributeError: 'module' object has no attribute 'get_version'
[17/Dec/2016 17:48:23] "GET / HTTP/1.1" 500 83849
```

**Comment by ad-m** [comment]
@hvilela , thank for you report. Did you use ``pip install django-guardian`` or install source code directly?

@brianmay , one more side-effect of scm? I am going to remove them on a new branch and I create pull requests. I replace them by bumpversion which is widely used.

**Comment by ad-m** [comment]
@hvilela , if you miss to execute ``pip install django-guardian`` as documented it is the fault code. ``pip install django-guardian`` might help as workaround. I am going to fix that.

**Comment by brianmay** [comment]
Apologies for the delay in responding. At a guess this problem can be fixed by running ``python ./setup.py --version`` which will force it to create the ``version.h`` file that is needed for the ``get_version()`` function.

**Comment by mikeengland** [comment]
@brianmay This fixed it for me too, thank you!
