### ISSUE TITLE
Django 1.11 compatibility

### ISSUE THREAD

**Issue by michael-k** [django-guardian/django-guardian#497]
I tried to add Django 1.11 to the test matrix. When adding it, `py.test --cov=guardian` fails with the following stack trace:

```python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.0/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/config.py", line 47, in main
    config = _prepareconfig(args, plugins)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/config.py", line 156, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/helpconfig.py", line 32, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/config.py", line 924, in pytest_cmdline_parse
    self.parse(args)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/config.py", line 1082, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/config.py", line 1053, in _preparse
    args=args, parser=self._parser)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/pytest_django/plugin.py", line 246, in pytest_load_initial_conftests
    _setup_django()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/pytest_django/plugin.py", line 149, in _setup_django
    django.setup()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/travis/build/michael-k/django-guardian/guardian/models.py", line 9, in <module>
    from guardian.managers import GroupObjectPermissionManager, UserObjectPermissionManager
  File "/home/travis/build/michael-k/django-guardian/guardian/managers.py", line 4, in <module>
    from guardian.core import ObjectPermissionChecker
  File "/home/travis/build/michael-k/django-guardian/guardian/core.py", line 7, in <module>
    from guardian.utils import get_group_obj_perms_model, get_identity, get_user_obj_perms_model
  File "/home/travis/build/michael-k/django-guardian/guardian/utils.py", line 12, in <module>
    from django.contrib.auth.views import redirect_to_login
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/django/contrib/auth/views.py", line 11, in <module>
    from django.contrib.auth.forms import (
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 20, in <module>
    UserModel = get_user_model()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 189, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/django/apps/registry.py", line 200, in get_model
    app_config.import_models()
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/travis/build/michael-k/django-guardian/guardian/testapp/models.py", line 9, in <module>
    from guardian.mixins import GuardianUserMixin
  File "/home/travis/build/michael-k/django-guardian/guardian/mixins.py", line 7, in <module>
    from guardian.models import UserObjectPermission
ImportError: cannot import name 'UserObjectPermission'
```

- complete test run on travis: https://travis-ci.org/michael-k/django-guardian/builds/217637266
- tested code: https://github.com/michael-k/django-guardian/tree/django-1.11

I reproduced this locally and with the help of git-bisect, it came down to Django's commit https://github.com/django/django/commit/cb7bbf97a74fa7800865e3615f196ad65dc4f281 from PR django/django#7550:
```
Fixed #25966 -- Made get_user_model() work at import time.
This makes it equivalent to: `from django.contrib.auth.models import User`.
```

Any idea on how to fix that?

**Comment by aaugustin** [comment]
You seem to have an import loop. `guardian.models` imports the custom User model in `testapp.models` which itself imports `guardian.models`.

You should restructure your imports to avoid a loop. I cannot say why this used to work.

**Comment by brianmay** [comment]
``guardian.models`` doesn't directly import ``testapp.models``.

Rather the sequence of imports is:
* ``guardian.models``
* ``guardian.managers`` 
* ``guardian.core``
* ``guardian.utils``
* ``django.contrib.auth.views``
* ``django.contrib.auth.forms``
  * this calls ``get_user_model()``

Which previously would have been OK, however now ``get_user_model()`` is an import it is not OK.

So it looks like we cannot import ``django.contrib.auth.views`` from ``guardian.models``.

**Comment by aaugustin** [comment]
Ah, I see.

I'm a bit surprise that `guardian.utils` import views. In order to be safe to import anywhere, utils modules shouldn't import higher level modules in general.

Sadly I don't have much better advice to offer than "figure out where you can break the import cycle; try to come up with a dependency tree where higher level modules import lower level modules, but never the opposite".

**Comment by michael-k** [comment]
> So it looks like we cannot import django.contrib.auth.views from guardian.models.

Good hint.  I found a fix, I guess. I'll send a PR in a few minutes.

**Comment by brianmay** [comment]
> I'm a bit surprise that guardian.utils import views.

Agreed, it seems strange that ``.models`` (indirectly) imports ``.views`` - should be the reverse.
