### ISSUE TITLE
django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.trib.auth.models.DoesNotExist: Permission matching query does not exist.

### ISSUE THREAD

**Issue by Allan-Nava** [django-guardian/django-guardian#540]
Hi,

i use this custom **perms.py** of [django-groups-manager](https://github.com/vittoriozamboni/django-groups-manager) and the error is:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/ies/bootcamp/bootcamp/groups_manager/models.py", line 145, in assign_object
    return assign_object_to_member(group_member, obj, **kwargs)
  File "/home/ies/bootcamp/bootcamp/groups_manager/perms.py", line 49, in assign_object_to_member
    assign_perm(perm_name, group_member.member.django_user, obj)
  File "/usr/local/lib/python3.5/dist-packages/guardian/shortcuts.py", line 105, in assign_perm
    return model.objects.assign_perm(perm, user, obj)
  File "/usr/local/lib/python3.5/dist-packages/guardian/managers.py", line 39, in assign_perm
    permission = Permission.objects.get(content_type=ctype, codename=perm)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.
```

![screen shot 2017-12-15 at 16 25 24](https://user-images.githubusercontent.com/22498435/34048604-a0909244-e1b4-11e7-82ba-9af98d369ed7.png)

**assign_object** -> https://github.com/vittoriozamboni/django-groups-manager/blob/master/groups_manager/models.py#L108

This is my perms.py
```
import copy

try:
    from guardian.shortcuts import assign_perm
except ImportError:
    def assign_perm(perm_name, group_or_user, obj):
        pass

from bootcamp.groups_manager.utils import get_permission_name


def assign_object_to_member(group_member, obj, **kwargs):
    """Assign an object to a GroupMember instance object.

    :Parameters:
      - `group_member`: groups_manager.model.GroupMember instance
      - `obj`: object to set permissions

    :Kwargs:
      - `custom_permissions`: updates settings.GROUPS_MANAGER['PERMISSIONS']
    """
    print("assign_object_to_member();")
    #SISTEMATO IL FOLDER DEI SETTAGGI
    from bootcamp.groups_manager.settings import GROUPS_MANAGER
    if GROUPS_MANAGER['AUTH_MODELS_SYNC'] and \
            group_member.group.django_group and group_member.member.django_user:
        roles_attr = kwargs.get('roles_attr', 'roles')
        print("roles_attr: "+str(roles_attr))
        permissions = copy.deepcopy(GROUPS_MANAGER['PERMISSIONS'])
        permissions.update(kwargs.get('custom_permissions', {}))
        # owner
        print("owner perms")
        if isinstance(permissions['owner'], dict):
            roles = getattr(group_member, roles_attr).values_list('codename', flat=True)
            print("roles: "+str(roles))
            owner_perms = []
            for role in list(set(roles).intersection(set(permissions['owner'].keys()))) + ['default']:
                owner_perms += permissions['owner'].get(role, [])
                print("owner_perms(role): "+str(owner_perms))
        else:
            owner_perms = permissions['owner']

        for permission in list(set(owner_perms)):
            perm_name = get_permission_name(permission, obj)
            print("permission for: "+str(owner_perms))
            print("perm_name: "+str(perm_name))
            print("obj: "+str(obj))
            assign_perm(perm_name, group_member.member.django_user, obj)

        print("group_perms")
        # group
        group_perms = permissions.get('group', [])
        for permission in list(set(group_perms)):
            perm_name = get_permission_name(permission, obj)
            assign_perm(perm_name, group_member.group.django_group, obj)
        
        print("groups_upstream")
        # groups_upstream
        upstream_groups = [group.django_group for group in group_member.group.get_ancestors()]
        upstream_perms = permissions.get('groups_upstream', [])
        for django_group in upstream_groups:
            for permission in list(set(upstream_perms)):
                perm_name = get_permission_name(permission, obj)
                print("upstream_groups: "+str(upstream_groups))
                print("perm_name: "+str(perm_name))
                print("obj: "+str(obj))
                assign_perm(perm_name, django_group, obj)
        
        print("downstream_groups")
        # groups_downstream
        downstream_groups = \
            [group.django_group for group in group_member.group.get_descendants()]
        downstream_perms = permissions.get('groups_downstream', [])
        for django_group in downstream_groups:
            for permission in list(set(downstream_perms)):
                perm_name = get_permission_name(permission, obj)
                print("downstream_perms: "+str(downstream_perms))
                print("perm_name: "+str(perm_name))
                print("obj: "+str(obj))
                assign_perm(perm_name, django_group, obj)

        print("downstream_groups")
        # groups_siblings
        siblings_groups = [group.django_group for group in group_member.group.get_siblings()]
        siblings_perms = permissions.get('groups_siblings', [])
        for django_group in siblings_groups:
            for permission in list(set(siblings_perms)):
                perm_name = get_permission_name(permission, obj)
                print("siblings_groups: "+str(siblings_groups))
                print("perm_name: "+str(perm_name))
                print("obj: "+str(obj))
                assign_perm(perm_name, django_group, obj)


def assign_object_to_group(group, obj, **kwargs):
 
    """Assign an object to a Group instance object.

    :Parameters:
      - `group`: groups_manager.model.Group instance
      - `obj`: object to set permissions

    :Kwargs:
      - `custom_permissions`: updates settings.GROUPS_MANAGER['PERMISSIONS']
    """
    print("assign_object_to_group")
    #SISTEMATO IL FOLDER DEI SETTAGGI
    from bootcamp.groups_manager.settings import GROUPS_MANAGER
    if GROUPS_MANAGER['AUTH_MODELS_SYNC'] and group.django_group:
        permissions = copy.deepcopy(GROUPS_MANAGER['PERMISSIONS'])
        permissions.update(kwargs.get('custom_permissions', {}))
        # owner is ignored from permissions
        print("permisions")
        print(permissions)
        # group
        group_perms = permissions.get('group', [])
        for permission in list(set(group_perms)):
            perm_name = get_permission_name(permission, obj)
            assign_perm(perm_name, group.django_group, obj)
        # groups_upstream
        upstream_groups = [ancestor_group.django_group for ancestor_group in group.get_ancestors()]
        upstream_perms = permissions.get('groups_upstream', [])
        for django_group in upstream_groups:
            for permission in list(set(upstream_perms)):
                perm_name = get_permission_name(permission, obj)
                assign_perm(perm_name, django_group, obj)
        # groups_downstream
        downstream_groups = \
            [downstream_group.django_group for downstream_group in group.get_descendants()]
        downstream_perms = permissions.get('groups_downstream', [])
        for django_group in downstream_groups:
            for permission in list(set(downstream_perms)):
                perm_name = get_permission_name(permission, obj)
                assign_perm(perm_name, django_group, obj)
        # groups_siblings
        siblings_groups = [sibling_group.django_group for sibling_group in group.get_siblings()]
        siblings_perms = permissions.get('groups_siblings', [])
        for django_group in siblings_groups:
            for permission in list(set(siblings_perms)):
                perm_name = get_permission_name(permission, obj)
                assign_perm(perm_name, django_group, obj)
```

**Comment by ad-m** [comment]
This is not a problem in this project. The repository is intended for a specific project, not for any problems with permissions in Django projects.
