### ISSUE TITLE
Error on migrate auth

### ISSUE THREAD

**Issue by pkerpedjiev** [django-guardian/django-guardian#542]
This error isn't expected, is it?

```
(cenv3) pete@twok:~/projects/blah [master|!?P]$ dropdb test; createdb test; python manage.py migrate auth;

Operations to perform:
  Apply all migrations: auth
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
Traceback (most recent call last):
  File "/Users/pete/miniconda3/envs/cenv3/lib/python3.6/site-packages/guardian/management/__init__.py", line 33, in create_anonymous_user
    User.objects.get(**lookup)
  File "/Users/pete/miniconda3/envs/cenv3/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pete/miniconda3/envs/cenv3/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
```

Running into this in Django 2.0.

**Comment by pkerpedjiev** [comment]
Never mind. It turns out that it was actually complaining about a relation to a table that hadn't been built by another migration yet. Ran the migrations for my app first and everything worked.
