### ISSUE TITLE
'Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by fabriziosestito** [django-guardian/django-guardian#570]
```
Django==2.0.5
django-guardian==1.4.9
django-haystack==2.8.1
django-stdimage==3.1.1
django-suit==0.2.26
elasticsearch==2.4.1
mysqlclient==1.3.12
Pillow==5.1.0
progressbar2==3.37.1
python-utils==2.3.0
pytz==2018.4
six==1.11.0
urllib3==1.22
```
Getting

```
  Applying guardian.0001_initial...Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 525, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 362, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/vagrant/.pyenv/versions/myproject/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
```

on MariaDB, database created with:
CREATE DATABASE mydatabase CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

**Comment by lainor** [comment]
I did a google search of course and I found the same solution using utf8 instead of utf8mb4,
which is not what I'm searching for since utf8 != utf8mb4.

On Mysql utf8 can only hold just 3 bytes per character, while utf8mb4 is the real 4 bytes utf8 encoding.

Any other solutions on this one?
This doesn't seem related to mariadb itself but to the migration.

**Comment by brianmay** [comment]
Fabrizio Sestito <notifications@github.com> writes:

> I did a google search of course and I found the same solution using utf8 instead of utf8mb4,
> which is not what I'm searching for since utf8 != utf8mb4.
>
> On Mysql utf8 can only hold just 3 bytes per character, while utf8mb4 is the real 4 bytes utf8 encoding.
>
> Any other solutions on this one?
> This doesn't seem related to mariadb itself but to the migration.

It is a mariadb/mysql limitation. My understanding is if you can upgrade
to the latest version of mariadb/mysql the problem should disappear.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by candlejack297** [comment]
I opened this a long time ago: https://github.com/django-guardian/django-guardian/issues/276

Using mysql's utf8 charset should be a no go since it's basically broken. 

The easiest hack would be to just change the migration (in your site_packages) to set the length to 191, run it, and reset the migration. Then you can just hope that no permission takes >191 chars.

An alternative would be to turn on innodb_large_prefix. https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix. There's a few other requirements to make this work, but I've used it successfully.

**Comment by thclark** [comment]
Closing as dupe of #276
