### ISSUE TITLE
ImportError: cannot import name 'patterns'  in django 2.0.5

### ISSUE THREAD

**Issue by Ardaq** [django-guardian/django-guardian#575]
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Ardaq\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\Ardaq\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 347, in execute
    django.setup()
  File "C:\Users\Ardaq\Anaconda3\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Ardaq\Anaconda3\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\Ardaq\Anaconda3\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Ardaq\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Ardaq\Anaconda3\lib\site-packages\guardian\models.py", line 16, in <module>
    from guardian.compat import user_model_label
  File "C:\Users\Ardaq\Anaconda3\lib\site-packages\guardian\compat.py", line 13, in <module>
    from django.conf.urls import url, patterns, include, handler404, handler500
ImportError: cannot import name 'patterns'

**Comment by typistX** [comment]
This has nothing to do with Guardian and everything to do with your Django version. A short Google search will elaborate.

**Comment by brianmay** [comment]
Errr... but the error is coming from `guardian\compat.py`, a file supplied by guardian.

**Comment by typistX** [comment]
If you import `patterns` from another file, does it throw the same error? AFAIK patterns is deprecated in Django 2. Have you upgraded recently?

**Comment by michael-k** [comment]
The `patterns` import was removed in commit 10baa22fa63c0fc593876ea6ee40a493730a33d7 which was part of the 1.4.2 release.

We're using version 1.4.9 in combination with Django 2.1.* without any problems.

@Ardaq can you close this issue?
