### ISSUE TITLE
assign_perm doesn't update db table

### ISSUE THREAD

**Issue by jdhurwitz** [django-guardian/django-guardian#576]
Here is my model that I'm trying to add create permission (and more custom ones later) to. The models.py file lives in my app directory which is named 'qa':

```
class Community(models.Model):
    name = models.CharField(max_length=20, unique=True)
    banner = models.ImageField(upload_to="communityBanners", blank=True)
    creation_date = models.DateTimeField(default=timezone.now)

    num_questions = models.IntegerField(default=0)
    num_answers = models.IntegerField(default=0)
    num_unanswered = models.IntegerField(default=0)

    class Meta:
        permissions = (
            ('create_community', 'Create community'),
        )

    def __str__(self):  # pragma: no cover
        return self.name
```

When I try to assign global permissions for this community objects to a specific user, my db does not update and has_perm returns false. Here is what I am doing in the shell:

```
from qa.models import *
from django.contrib.auth.models import User
from guardian.shortcuts import *

v = User.objects.get(username='vic')
v.is_active //prints true
assign_perm('qa.create_community', v) //prints out a permissions obj + no errors
v.has_perm('qa.create_community) //**prints FALSE**

```

I've also tried doing v.save() after assigning the perm.

**Comment by typistX** [comment]
I’m betting it’s this line:


```
assign_perm('qa.create_community', v)
```

try changing the first argument to `create_community`

**Comment by sdimovv** [comment]
4 years later I have the same problem...

Here is a snippet from the console:
```
>>> user.has_perm('myapp.view_mymodel')
False
>>> assign_perm('myapp.view_mymodel', user)
<Permission: myapp | mymodel | Can view mymodel>
>>> user.has_perm('myapp.view_mymodel')
False
>>> assign_perm('myapp.view_mymodel', user)
<Permission: myapp | mymodel | Can view mymodel>
>>> assign_perm('myapp.view_mymodel', user).save()
>>> user.has_perm('myapp.view_mymodel')
False
>>> assign_perm('myapps.view_mymodel', user).save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".../.venv/lib/python3.9/site-packages/guardian/shortcuts.py", line 95, in assign_perm
    perm = Permission.objects.get(content_type__app_label=app_label,
  File ".../.venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File ".../.venv/lib/python3.9/site-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Permission.DoesNotExist: Permission matching query does not exist.
```

@jdhurwitz did you manage to solve it?

**Comment by thclark** [comment]
When getting `django.contrib.auth.models.Permission.DoesNotExist: Permission matching query does not exist.` you probably want to first run `makemigrations` which will create the permission on the object.

This isn't strictly part of guardian, it's part of django's auth system, so I'm closing but hopefully searches will bring people to this solution.
