### ISSUE TITLE
Error in `create_anonymous_user` when running migrations despite success

### ISSUE THREAD

**Issue by kurtwheeler** [django-guardian/django-guardian#698]
When I run my migrations against a fresh database I get an `django.db.utils.ProgrammingError: relation "authtoken_token" does not exist` error originating from `create_anonymous_user`. This happens even when starting with a completely fresh database and no migrations.

However, this doesn't actually seem to cause any issues. The migrations still applied successfully, and subsequent runs of the `migrate` command happily report there's nothing more to do.

```
kurt:~/Development/resources-portal$ docker-compose run --rm api ./manage.py makemigrations resources_portal
Creating resourcesportal_postgres_1 ... 
Creating resourcesportal_postgres_1 ... done
Creating elasticsearch ... 
Creating elasticsearch ... done
Migrations for 'resources_portal':
  resources_portal/migrations/0001_initial.py
    - Create model User
    - Create model Attachment
    - Create model Material
    - Create model Organization
    - Create model ShippingInformation
    - Create model OrganizationUserSetting
    - Create model OrganizationUserAssociation
    - Create model OrganizationInvitation
    - Add field members to organization
    - Add field owner to organization
    - Create model MaterialShareEvent
    - Create model MaterialRequest
    - Add field organization to material
    - Add field shipping_information to material
    - Create model Grant
    - Add field sequence_map_for to attachment
    - Add field organizations to user
    - Add field user_permissions to user

kurt:~/Development/resources-portal$ docker-compose run --rm api ./manage.py makemigrations resources_portal
Starting resourcesportal_postgres_1 ... done
Starting elasticsearch ... done
No changes detected in app 'resources_portal'

kurt:~/Development/resources-portal$ docker-compose run --rm api ./manage.py migrate resources_portal
Starting resourcesportal_postgres_1 ... done
Starting elasticsearch ... done
Operations to perform:
  Apply all migrations: resources_portal
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying resources_portal.0001_initial... OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/guardian/management/__init__.py", line 32, in create_anonymous_user
    User.objects.using(kwargs['using']).get(**lookup)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
resources_portal.models.user.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "authtoken_token" does not exist
LINE 1: INSERT INTO "authtoken_token" ("key", "user_id", "created") ...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 30, in <module>
    main()
  File "./manage.py", line 26, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 256, in handle
    emit_post_migrate_signal(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/sql.py", line 45, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.8/site-packages/guardian/management/__init__.py", line 37, in create_anonymous_user
    user.save(using=kwargs['using'])
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 740, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 788, in save_base
    post_save.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 173, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 174, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/user/code/resources_portal/models/user.py", line 26, in create_auth_token
    Token.objects.create(user=instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/authtoken/models.py", line 35, in save
    return super(Token, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 740, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 777, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 907, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1375, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "authtoken_token" does not exist
LINE 1: INSERT INTO "authtoken_token" ("key", "user_id", "created") ...
                    ^
kurt:~/Development/resources-portal$ docker-compose run --rm api ./manage.py migrate resources_portal
Starting resourcesportal_postgres_1 ... done
Starting elasticsearch ... done
Operations to perform:
  Apply all migrations: resources_portal
Running migrations:
  No migrations to apply.
```

Any ideas why this error is being raised and what I can do about it? If it'd be helpful to see the source code my project is open source and can be found in the `api` directory of https://github.com/AlexsLemonade/resources-portal.

Thank you!

**Comment by kurtwheeler** [comment]
Sorry, I think this might be an issue with django rest framework instead. I'll reopen if I change my mind again.
