### ISSUE TITLE
get_objects_for_group expects Group instance and raises error during the django migration

### ISSUE THREAD

**Issue by ipanova** [django-guardian/django-guardian#751]
```
Groups = apps.get_model('auth', 'Group')
groups_ns1 = Groups.objects.filter(name__regex=r'container.(distribution|namespace).(collaborators|owners)')
type(groups_ns1[0])
Out[18]: __fake__.Group
get_objects_for_group(groups_ns1[0], 'container.modify_content_containerpushrepository', accept_global_perms=False)
Traceback (most recent call last):
  File "/usr/local/lib/pulp/lib64/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-6344fd0770a3>", line 1, in <module>
    get_objects_for_group(groups_ns1[0], 'container.modify_content_containerpushrepository', accept_global_perms=False)
  File "/usr/local/lib/pulp/lib64/python3.8/site-packages/guardian/shortcuts.py", line 766, in get_objects_for_group
    groups_obj_perms_queryset = (group_model.objects
  File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/db/models/sql/query.py", line 1315, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/db/models/sql/query.py", line 1224, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/db/models/sql/query.py", line 1084, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "/usr/local/lib/pulp/lib64/python3.8/site-packages/django/db/models/sql/query.py", line 1065, in check_query_object_type
    raise ValueError(
ValueError: Cannot query "Group object (1)": Must be "Group" instance.

```

more context  on this PR https://github.com/pulp/pulp_container/pull/320/files#r657987757
**Version: django-guardian==2.3.0**

**Comment by dralley** [comment]
The latest commit to this repo touched this line, so it might be worthwhile to try the dev branch.

https://github.com/django-guardian/django-guardian/commit/1c74f2491bd5aba21c8fa9fdcf3cd1cc5c007382

**Comment by ad-m** [comment]
@ipanova could you provide isolated example or provide pull request to handle that scenario?

**Comment by Enase** [comment]
I have the same issue in migration, you can reproduce it in this way:

1. Add custom migration:
```

def populate_groups(apps, _schema_editor):
    test_group, _ = group_model.objects.get_or_create(name="test_group")


    some_model = apps.get_model("label", "some_model")
    permissions = get_perms_for_model(some_model)
    for perm in permissions:
        assign_perm(f"label.{perm.codename}", test_group, obj=None)
        

    // somewhere in migration operations add:
    migrations.RunPython(populate_groups),
```

2. Execute it twice: first time `test_group` do not exists and second time `test_group` exists in DB.

Expected: no errors
current result: `guardian.exceptions.NotUserNorGroup: User/AnonymousUser or Group instance is required (got Group object (1))`

**Comment by Enase** [comment]
answer my question:
while migrations django uses [historical-models](https://docs.djangoproject.com/en/4.1/topics/migrations/#historical-models). In my case I need to import models directly.

**Comment by kmmbvnr** [comment]
Could it be just fixed by using separate data migration, with direct models import?

**Comment by thclark** [comment]
Suspect this is due to incorrect use of django's (quite unintuitive!) historical models. Closing.
