### ISSUE TITLE
Unable to create anonymous user

### ISSUE THREAD

**Issue by zesameri** [django-guardian/django-guardian#794]
I am following the initial set up from [the configuration set up doc ](https://django-guardian.readthedocs.io/en/stable/configuration.html). After adding in the appropriate settings, and running manage.py migrate I get the two following errors: 
- `ValueError: badly formed hexadecimal UUID string`
- `django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']`

Here is the stack trace
```
  Applying guardian.0001_initial... OK
  Applying guardian.0002_generic_permissions_index... OK
Traceback (most recent call last):
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2649, in to_python
    return uuid.UUID(**{input_form: value})
  File "/home/merhoo/miniconda3/lib/python3.9/uuid.py", line 177, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/merhoo/GitHub/wand/wand-django/web/manage.py", line 24, in <module>
    main()
  File "/home/merhoo/GitHub/wand/wand-django/web/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 376, in handle
    emit_post_migrate_signal(
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/core/management/sql.py", line 52, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 66, in wrapper
    return receiver(*args, **kwargs)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/guardian/management/__init__.py", line 32, in create_anonymous_user
    User.objects.using(kwargs['using']).get(**lookup)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2633, in get_prep_value
    return self.to_python(value)
  File "/home/merhoo/GitHub/wand/wand-django/web/.venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 2651, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“AnonymousUser” is not a valid UUID.']
```
In the aforementioned docs, it notes that 

> The Guardian anonymous user is different from the Django Anonymous user. The Django Anonymous user does not have an entry in the database, however the Guardian anonymous user does.

Our User model's index is a UUID and I think that the guardian code is trying to create a user assuming its an AbstractBaseUser:

`uuid = models.UUIDField(unique=True, db_index=True, default=uuid.uuid4, editable=False)`

I'm not sure how to fix this issue, any and all advice is appreciated

**Comment by zesameri** [comment]
I found [this docs about custom User models](https://django-guardian.readthedocs.io/en/stable/userguide/custom-user-model.html). I will post a follow up once I confirm its fixed

**Comment by dashdanw** [comment]
Guardian is throwing an error because it's default username `AnyonymousUser` is not of type `UUID` , to fix this you can set `ANONYMOUS_DEFAULT_USERNAME_VALUE` in your `settings.py`.

Here's the pertinent code:
https://github.com/django-guardian/django-guardian/blob/devel/guardian/management/__init__.py#L31

**Comment by zesameri** [comment]
This worked thank you so much :0)
